### PR TITLE
local file storage driver

### PR DESCRIPTION
**Pull request by shahidkarimi**
Enable file local file storage if a env config `STORAGE_DRIVER` found in the .env file.
So `STORAGE_DRIVER=local'  means local storage otherwise aws s3.

### CODE REVIEW

**Comment by harshbinjwa** [comment]
Hi shahidkarimi,
I am getting an error while adding images in the room type and rate plan on minical when I am using a local storage drive.
can you please check?
Screenshot12
Screenshot11

**Comment by shahidkarimi** [comment]
I will look into it. BTW your public/upload must be writable

**Comment by shahidkarimi** [comment]
@harshbinjwa thanks for the review.
1- The first issue is not related to file upload. That js issue appears when the page is loaded
2- The folder `public/uploads` needs to be writable
The file upload is fixed.

**Comment by harshbinjwa** [comment]
[shahidkarimi](https://github.com/shahidkarimi) 
Hi , there are still some issue. now I have provided full write permission to folder directory
1) still room type and rate plan images not uploading showing fail issue on crop function.
Screenshot03

2) image is uploading at company general information but not instantly show as preview, after page reload then it's up and show full image path and preview. 
Screenshot01

3) if we  had used AWS_S3_BUCKET and then enables local storage driver as local host so AWS image gone corrupt. but it should not show there if local storage enable. we need to set a process so that the will not effect each other.
Screenshot02

**Pull request closed without merging**
